HomeIS/Models/Apartment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HomeIS.Models
{
    public class Apartment
    {
        public int ID { get; set; }
        public Location Location { get; set; }
        public ApplicationUser Owner { get; set; }
        public string Description { get; set; }
        public int PropertyValue { get; set; }
        public int NumberOfRooms { get; set; }
        public int Size { get; set; }
        public bool Balcony { get; set; }
        public int FloorNumber { get; set; }
        public bool IsForSale { get; set; }


        // Entity Framework can't save an array
        public List<string> PhotoList { get; set; }

        public string Photos
        {
            get => (PhotoList == null || PhotoList.Count <= 0 ? "" : string.Join(",", PhotoList));
            set => PhotoList = (string.IsNullOrEmpty(value) ? new List<string>() : value.Split(',').ToList());
        }
    }
}

HomeIS/Controllers/ApartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HomeIS.Models;
using Microsoft.ApplicationInsights.Web;

namespace HomeIS.Controllers
{
    public class ApartmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Apartments
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Apartments.Where(ap =>
                ap.Owner == db.Users.FirstOrDefault<ApplicationUser>(user =>
                    user.UserName == this.User.Identity.Name)));
        }

        // GET: Apartments/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Apartment apartment = db.Apartments.FirstOrDefault(ap => (ap.ID == id) &&
                                                                      (ap.Owner.UserName == this.User.Identity.Name));

            if (apartment == null)
            {
                return HttpNotFound();
            }

            return View(apartment);
        }

        // GET: Apartments/Create
        [Authorize]
        public ActionResult Create()
        {
            return View(); 
        }

        // POST: Apartments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include =
                "ID,Owner,Location,Description,PropertyValue,PhotoList,Photos,Balcony,Size,FloorNumber,NumberOfRooms")]
            Apartment apartment)
        {
            db.Configuration.LazyLoadingEnabled = false;


            List<string> PhotoList = new List<string>();

            if (ModelState.IsValid && Request.Files.Count > 0)
            {
                for (int uploadID = 0; uploadID < Request.Files.Count; uploadID++)
                {
                    var uploadedFile = Request.Files[uploadID];

                    if (uploadedFile.HasFile())
                    {
                        PhotoList.Add(UploadApartmentPhoto(uploadedFile));
                    }
                }

                apartment.PhotoList = PhotoList;
                apartment.Owner = db.Users.FirstOrDefault(s => s.UserName == this.User.Identity.Name);

                db.Apartments.Add(apartment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(apartment);
        }

        private string UploadApartmentPhoto(HttpPostedFileBase uploadedFile)
        {
            string relativePath = "UserPhotos/" + this.User.Identity.Name.Replace("@", "------");
            string absolutePath = AppDomain.CurrentDomain.BaseDirectory + relativePath;

            Directory.CreateDirectory(absolutePath);

            string filename = DateTime.Now.ToFileTime() + (new Random().Next()).ToString() +
                              Path.GetExtension(uploadedFile.FileName);
            uploadedFile.SaveAs(Path.Combine(absolutePath, filename));

            return relativePath + '/' + filename;
        }

        // GET: Apartments/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            db.Configuration.LazyLoadingEnabled = false;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Apartment apartment = db.Apartments.FirstOrDefault(ap => (ap.ID == id) &&
                                                                      (ap.Owner.UserName == this.User.Identity.Name));

            if (apartment == null)
            {
                return HttpNotFound();
            }

            return View(apartment);
        }

        // POST: Apartments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include =
                "ID,Owner,Location,Description,PropertyValue,PhotoList,Photos,Balcony,Size,FloorNumber,NumberOfRooms")]
            Apartment apartment)
        {
            if (ModelState.IsValid)
            {
                for (int uploadID = 0; uploadID < Request.Files.Count; uploadID++)
                {
                    var uploadedFile = Request.Files[uploadID];

                    if (uploadedFile.HasFile())
                    {
                        apartment.PhotoList.Add(UploadApartmentPhoto(uploadedFile));
                    }
                }

                // Compare and delete all the photos from the folder
                CompareAndDeletePhotos(apartment);

                db.Entry(apartment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(apartment);
        }

        private void CompareAndDeletePhotos(Apartment apartment)
        {
            // Get the current db value
            string dbApartmentPhotoList =
                db.Apartments.Where(ap => ap.ID == apartment.ID).Select(ap => ap.Photos).ToList()[0];

            if (!String.IsNullOrEmpty(dbApartmentPhotoList))
            {
                foreach (string photo in dbApartmentPhotoList.Split(','))
                {
                    string filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, photo);

                    if (!apartment.PhotoList.Contains(photo) && System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }
                }
            }
        }

        // GET: Apartments/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Apartment apartment = db.Apartments.FirstOrDefault(ap => (ap.ID == id) &&
                                                                      (ap.Owner.UserName == this.User.Identity.Name));

            if (apartment == null)
            {
                return HttpNotFound();
            }

            return View(apartment);
        }

        // POST: Apartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Apartment apartment = db.Apartments.FirstOrDefault(ap => (ap.ID == id) &&
                                                                      (ap.Owner.UserName == this.User.Identity.Name));

            if (apartment != null)
            {
                apartment.PhotoList.ForEach(photo => System.IO.File.Delete(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, photo)));

                db.Apartments.Remove(apartment);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }

        public JsonResult AllApartmentsJSON()
        {
            var apartments = db.Apartments.ToList();
            return Json(apartments, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ApartmentCountGroupJSON()
        {
            var apartments = db.Apartments.GroupBy(ap => ap.Location.City)
                                          .Select(ap => new {City = ap.Key, Count = ap.Count()});

            return Json(apartments, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SizeBalconyMinOrMaxPriceJSON(int Size, bool Balcony, int MinimumPrice)
        {
            return Json(db.Apartments.Include(t => t.Owner).Where(p => p.Balcony == Balcony && p.Size == Size &&
                                                                       p.PropertyValue >= MinimumPrice).ToList(),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult SizeBalconyPriceRangeJSON(int Size, bool Balcony, int MinimumPrice, int MaximumPrice)
        {
            var QuerySet = db.Apartments.Include(t => t.Owner).Where(p => p.Balcony == Balcony && p.Size == Size &&
                                                                          p.PropertyValue >= MinimumPrice &&
                                                                          p.PropertyValue <= MaximumPrice).ToList();
            return Json(QuerySet, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AmountPerCity(string CityName)
        {
            var QuerySet = db.Apartments.Where(t => t.Location.City == CityName).GroupBy(p => p.Location.City)
                .Select(g => new {count = g.Count()}).ToList();

            return Json(QuerySet, JsonRequestBehavior.AllowGet);
        }

        public bool PredictApartmentSale(int size, int value, int floor)
        {

            var proc = new Process
            {
                StartInfo = new ProcessStartInfo
                {
                    FileName = System.AppDomain.CurrentDomain.BaseDirectory + @"..\debug\ML.exe",
                    Arguments = size.ToString() +" "+ value.ToString() +" "+ floor.ToString(),
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    CreateNoWindow = false
                }
            };

HomeIS/Views/Apartments/Create.cshtml
@model HomeIS.Models.Apartment

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Apartments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
    <h4>Apartment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PropertyValue, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PropertyValue, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PropertyValue, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumberOfRooms, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumberOfRooms, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumberOfRooms, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Balcony, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Balcony)
                @Html.ValidationMessageFor(model => model.Balcony, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FloorNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FloorNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FloorNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Photos, htmlAttributes: new { @class = "control-label col-md-2" })
        <small>Total size limit: 10MB</small>
        <div class="col-md-10">
            <input class="input-validation-error form-control" data-val-required="You need to upload photos" data-val="true" type="file" name="Photos" id="Photos" accept="image/*" multiple Required/>
            @Html.ValidationMessageFor(model => model.Photos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div class="cool-wrapper">
    <span class="cool-square">
        <a class="cool-a-tag before after" href="~/Apartments/Index">Back To List</a>
    </span>
</div>

HomeIS/Views/Apartments/Delete.cshtml
@model HomeIS.Models.Apartment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Apartment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PropertyValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PropertyValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfRooms)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfRooms)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balcony)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balcony)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FloorNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FloorNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photos)
        </dt>

        <dd>
            @foreach (var photo in Model.PhotoList)
            {
                if (photo.Contains("http"))
                {
                    <img class="apartment-view-image" src="@photo" />
                }
                else
                {
                    <img class="apartment-view-image" src="../../@photo" />
                }
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
        </div>
    }
</div>

<br />
<br />

<div class="cool-wrapper">
    <span class="cool-square">
        <a class="cool-a-tag before after" href="~/Apartments/">Back To List</a>
    </span>
</div>

HomeIS/Views/Apartments/Details.cshtml
@model HomeIS.Models.Apartment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Apartment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PropertyValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PropertyValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfRooms)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfRooms)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balcony)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balcony)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FloorNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FloorNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photos)
        </dt>

        <dd>
            @foreach (var photo in Model.PhotoList)
            {
                if (photo.Contains("http"))
                {
                    <img class="apartment-view-image" src="@photo" />
                }
                else
                {
                    <img class="apartment-view-image" src="../../@photo" />
                }
            }
        </dd>

    </dl>
</div>

<div>
    <div class="cool-wrapper" style="float: left;">
        <span class="cool-square">
            @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "cool-a-tag before after" })
        </span>
    </div>

    <div class="cool-wrapper" style="margin-left: 30%;">
        <span class="cool-square">
            <a class="cool-a-tag before after" href="~/Apartments/">Back to List</a>
        </span>
    </div>
</div>

HomeIS/Views/Apartments/Edit.cshtml
@model HomeIS.Models.Apartment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Apartments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Apartment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropertyValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PropertyValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PropertyValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfRooms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfRooms, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfRooms, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Balcony, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Balcony)
                    @Html.ValidationMessageFor(model => model.Balcony, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FloorNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FloorNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FloorNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.Photos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Photos</label>
            <div class="col-md-10">
                @foreach (var photo in Model.PhotoList)
                {
                    string photoItem = photo;

                    if (!photo.Contains("http"))
                    {
                        photoItem = "../../" + photo;
                    }

                    <div class="apartment-view-image-container">
                        <img class="apartment-view-image" src="@photoItem" />
                        <div class="apartment-view-image-overlay ">
                            <a class="apartment-view-image-delete-button" data-img="@photo" href="javascript:void(0);" style="color:transparent"><span class="glyphicon glyphicon-remove apartment-view-image-container-delete" /></a>
                        </div>
                    </div>
                }
            </div>

        </div>

        <div class="form-group">
            <label class="control-label col-md-2"> Upload More Photos: <small>Total size limit: 10MB</small></label>
            <div class="col-md-10">
                <input type="file" name="Photos" id="Photos" accept="image/*" multiple />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<br />
<div class="cool-wrapper">
    <span class="cool-square">
        <a class="cool-a-tag before after" href="~/Apartments/">Back To List</a>
    </span>
</div>

HomeIS/Views/Apartments/Index.cshtml
@model IEnumerable<HomeIS.Models.Apartment>

@{
    ViewBag.Title = "My Apartments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<br />
<div class="cool-wrapper">
    <span class="cool-square">
        <a class="cool-a-tag before after" href="~/Apartments/Create">Create New</a>
    </span>
</div>
<br />

<table class="table">
    <tr>
        <th class="th-width-20">
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th class="th-width-15">
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th class="th-width-15">
            Number Of Rooms
        </th>
        <th class="th-width-35">
            @Html.DisplayNameFor(model => model.Photos)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <label>City: </label> @Html.DisplayFor(modelItem => item.Location.City)
            <br />
            <label>Neighborhood: </label> @Html.DisplayFor(modelItem => item.Location.Neighborhood)
            <br />
            <label>Address: </label> @Html.DisplayFor(modelItem => item.Location.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfRooms)
        </td>
        <td>
            @if(item.PhotoList != null)
            {
                foreach (var photo in item.PhotoList)
                {
                        <img class="apartment-view-image" src="@photo" />
                }
            }
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
        </td>
    </tr>
}

</table>